behaviors:
    default:
        trainer_type: ppo
        hyperparameters:
            batch_size: 512 
            buffer_size: 5120
            learning_rate_schedule: linear
            learning_rate: 3.0e-4
        network_settings:
            hidden_units: 512
            normalize: false
            num_layers: 4
            vis_encode_type: simple
            memory:
                memory_size: 512
                sequence_length: 512
        max_steps: 10.0e5
        time_horizon: 64    
        summary_freq: 10000
        reward_signals:
            extrinsic:
                strength: 1.0
                gamma: 0.99
    Autopark:
        trainer_type: ppo
        hyperparameters:
            batch_size: 512
            buffer_size: 5120
        network_settings:
            hidden_units: 512
            num_layers: 4
        max_steps: 10.0e6
        time_horizon: 128
